In [1]:
import ktbFantasyFootball as ktb
import pandas as pd


ktb_getter = ktb.ktb(
    browser_path = '..\\browsers\\geckodriver.exe',
    database_export = True, 
    store_locally=True, 
    config_path = '..\\..\\..\\Notes-General\\config.txt',
    league_id = 245118,
    league_cookies = {
        "SWID":"{53904938-E572-4FD1-9F30-10A8A39DA775}",
        "espn_s2":"AEBvpGk1SP6ibJZS7FOb%2Fj96G4TZWJrrUKPGNpWRagAthxCljUQkzY7J6sxAt%2Bezfk9fygiXuoY1aBehpYE0m4n7L%2BwbOJXPBOVp10dpJ3BXGwLy9RB5HI%2FNAOnL4czsqizbi%2FPdMexDbiLunx35kXtV4JWzlc3UqS%2Fkvqw6%2F58pzotJFoF%2FTK3mCgUyherJPFl26P5ItBVe2dGf6Y0%2B2WDjiDOLAh4xeXDggKVyoOxBoGZT4ODtKLk9agSEmSG9zwz73MGF6JerNaTg%2BcPKxRZex6f9caDHD%2BSxj2zcwh3q6w%3D%3D"
    },
    league_headers = {
        'X-Fantasy-Filter': '{"players": {"limit": 1500, "sortPercOwned":{"sortAsc":false,"sortPriority":1}}}'
    }
)

In [2]:
df = ktb_getter.get_league_history(2024,            
        endpoints = ['mTeam','mBoxscore', 'mRoster','mSettings','kona_player_info','player_wl','mSchedule'],
        base_url = 'https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/{}/segments/0/leagues/{}?view=mLiveScoring&view=mMatchupScore&view=mRoster&view=mSettings&view=mStandings&view=mStatus&view=mTeam&view=modular&view=mNav',
        json_output_path = '..\\data\\League History\\{s}-{f}_league_history.txt',
        save_json = False,
        process_json_to_df = True,
        database_table_teams = 'ktbteams'
    )

successfully added data

In [3]:
df[1]

,season,teamId,teamName,abbr,wins,losses,ties,pf,pa,pfAllSeason,rankRegSeason,rankFinalCalc,streak,streakType,budgetSpent,acqs,drops,draftDayProjRank,pick,rankFinalKtb
0,2024,1,Jamo no Chaser,jb,12,2,0,1777.56,1477.00,1777.56,1,1,5,WIN,500,45,45,2,6,None
1,2024,2,Team Gomer,GOMR,8,6,0,1753.78,1741.98,1753.78,3,5,1,WIN,437,18,18,10,2,None
2,2024,3,DPD DannyDimes,Pope,5,9,0,1636.08,1781.54,1636.08,11,7,2,LOSS,480,15,14,1,12,None
3,2024,4,Poopstained Warriors,JPAW,7,7,0,1441.72,1497.56,1441.72,6,4,2,WIN,275,17,17,6,4,None
4,2024,5,JB got last in 23,GEIK,8,6,0,1724.12,1567.60,1724.12,4,3,1,LOSS,60,11,10,12,8,None
5,2024,6,Purdy Chubby,BFJ,2,12,0,1324.78,1592.12,1324.78,12,12,6,LOSS,491,31,32,11,5,None
6,2024,7,Team Chaunce,Chnc,8,6,0,1627.86,1533.72,1627.86,5,6,2,WIN,463,20,19,7,10,None
7,2024,8,Touchdown My Pants,Tits,10,4,0,1682.42,1596.58,1682.42,2,2,3,WIN,50,7,7,9,9,None
8,2024,9,Big Baby Nate,Nate,6,8,0,1488.50,1498.28,1488.50,9,10,2,LOSS,206,16,16,8,3,None
9,2024,10,CeeDeez Nutz,MURF,6,8,0,1517.28,1583.60,1517.28,8,8,2,LOSS,292,12,12,5,7,None
10,2024,11,The Suavin Scoregasms,Kir1,6,8,0,1611.22,1542.62,1611.22,7,9,2,WIN,365,15,15,4,11,None
11,2024,12,free breece,emj,6,8,0,1474.98,1647.70,1474.98,10,11,3,LOSS,97,43,53,3,1,None

In [46]:
a = pd.read_sql_query(
    sql ='SELECT teamId, pick FROM ktbdrafts WHERE season = %s and round = 1',
    con = ktb_getter.pymysql_conn_str,
    params= (2024,)
)

In [52]:
dict(zip(a['teamId'], a['pick']))

{12.0: 1,
 2.0: 2,
 9.0: 3,
 4.0: 4,
 6.0: 5,
 1.0: 6,
 10.0: 7,
 5.0: 8,
 8.0: 9,
 7.0: 10,
 11.0: 11,
 3.0: 12}

Object `pd.to_dict()` not found.

In [19]:
def a(x, y=0, z=0):
    for i in x:
        print(i**2 - 1)

In [20]:
x = [-3, -1]
a(x)

8
0

In [12]:
(-5 - (-3)) / (-2 - 2)

0.5